### ISSUE TITLE
force little endianness on read/write

### ISSUE THREAD

**Issue by kylerbrown** [kylerbrown/bark#13]
... or update docs to say 'native ordering' instead of 'little-endian'

**Comment by kylerbrown** [comment]
Another option is to require the dtype to include the endianness for multibyte numbers.

Reference: https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

For example:
+ `<i2` is little endian int16,
+ `<f8` is little endian double precision float

I dislike these short codes because there are a little confusing to parse (`<int16`doesn't work, only `<i2`), but probably the simplest system to implement is requiring a "<" or ">" if the number is two or more bytes.

Portability!

@gfetterman

**Comment by gfetterman** [comment]
Let's use the byte-order-aware dtypes, and let numpy handle everything.

I prefer this solution over talking about native byte ordering - i.e., the byte ordering of the system Bark is running on. Let's be as simple and explicit as possible.

Then the docs would be modified to say something like "`dtype` must include endianness. Bark can safely handle either byte ordering."

**Comment by kylerbrown** [comment]
backwards compatible fix by https://github.com/kylerbrown/bark/commit/eb36e21ed3992934f5d5d4be0abf0295867068a3
