### ISSUE TITLE
map bark spec to a relational database schema

### ISSUE THREAD

**Issue by kylerbrown** [kylerbrown/bark#21]
include a tool to create an sqlite database from entries

**Comment by kylerbrown** [comment]
@gfetterman  the time has come

**Comment by gfetterman** [comment]
Nooooooo.

Alright, some questions:

1. Why now? AYGNI?
2. Granted that a DB is the way to go for lots and lots of records, is it necessary here? It wouldn't be part of Bark itself, but slurping all metadata into a binary file is rather anti-Bark-ian. Something lighter, perhaps that takes a directory and produces some representation of the tree structure beneath it containing Entries, might meet most needs. `grep`+Bark is already ~75% of the way to an SQL interface to metadata. This would also sidestep the staleness problem.
3. Assuming your answers to (1) and (2) are "Yes" and "No it's gotta be a DB", how are we going to interface with it? Hand-coding SQL is error-prone, but using an ORM like SQLAlchemy adds a (pretty meaty) dependency.
4. Is Bark-to-SQL-schema a natural mapping? There are very few required metadata fields, so most metadata would be represented in potentially low-overlap one-to-many and many-to-many mappings.

**Comment by kylerbrown** [comment]
@gfetterman 
1. I'm starting to need answers to questions like how many neurons for bird x? How many motifs per day? I'd like some additional structure that give me summary data for what kind of data I have.
2. Grep does get me part of the way there, that's true. But SQL is a more natural fit. If I can get SQL for cheap, I'm interested. Also future (small) GUIs could have a DB backend.
3. SQLite + SQLAlchemy is bit of a dependency burden, this may exist outside the bark repo. That said, with these dependencies in place I don't think we'd need much new code to build a schema. I've seen it work [pretty well in other simple projects](https://github.com/Data4Democracy/collect-social/blob/master/collect_social/facebook/utils.py). SQLite doesn't require any special permissions or daemons, it's just one file. 
4. That is the question! I'm thinking: 
    + An Entry table. fields are at minimum the metadata attributes
    + Events: Each row would be a record. ARF datatypes don't have required fields but some of them have natural requirements: Stimuli need a start and a name, behaviors need a start, stop and name. Spikes need a start, name and channel. etc... We can also dynamically add fields based on CSV fields and metadata attributes, so there would be some flexibility to add whatever you put in. 
    + For Sampled datasets, a record for each column. Possibly different tables for datatypes.

**Comment by gfetterman** [comment]
Ok. I've used SQLAlchemy but not `dataset` before. Looks to simplify things quite a bit.

So are you proposing to make each event dataset into its own table in the DB? Or am I misreading your point (4)? Related, I suppose: does each Bark "tree" have its own DB, or does a single DB serve to contain all of your (or the lab's) data?

**Comment by kylerbrown** [comment]
I think a table for each dataset type. The interface would be a tool to add
entries to the DB. So a DB could be for one bird, one experiment or one lab.

**Comment by gfetterman** [comment]
And then interesting post-analysis data - like # of motifs per day, or # of neurons per bird-day - would be additional fields for the appropriate datasets?

**Comment by kylerbrown** [comment]
@gfetterman I think those would be queries or views on the data. For relational inspiration, here is Neo's object model. 

![Neo object model](https://pythonhosted.org/neo/_images/simple_generated_diagram.png)

I think we could distill this down a bit and create something that fits bark. 

Also I'm not crazy about ARF's datatype system, eg 2002 being label data. I think I'd prefer something like a 'class' attribute with readable values, like `class: spike` or `class: stimulus`. Then we would use this to load spikes or stimuli into their respective correct tables. We could also have something like `sampled: hvc.dat` to associate spikes to their original sampled dataset.

Classes and their associated fields and metadata wouldn't be part of the spec, or would be optional.

**Comment by gfetterman** [comment]
So for sampled datasets, the database contains only the metadata, but for event datasets, the database contains the entirety of the dataset plus its metadata?

I.e., if there's a table for Arf datatype 1000 ("EVENT"), then every row of every event dataset matching that datatype is a row in the DB table?

**Comment by kylerbrown** [comment]
Yeah that's what I'm imagining

**Comment by gfetterman** [comment]
Ok - a couple more things, and then I'll hold my peace.

This feels like trying to squeeze two different sets of functionality into a single DB.

I don't see any benefit to generating the post-analysis data within the DB rather than through a python script. You gain little - if anything - in expressiveness by substituting SQL access to a DB in place of pythonic access to dicts/dataframes.

And you
* add an additional layer of conceptual abstraction
* add a new data format
* add a new method of access - either raw SQL, or the `dataset` ORM
* duplicate all of your event data - in a binary format, no less
* have to worry about stale DB data

If in spite of all this you're sure that this is what you need, perhaps consider making this a standalone project, and not part of Bark. It seems to cut against the simplicity of the format.

Alternatively, you could separate the metadata DB, which would be broadly applicable to Bark data, from the low-level event dataset query functionality, which would be much more user-specific.

**Comment by kylerbrown** [comment]
Those are great points Graham,

I've come to the conclusion that the problem is that Bark only supports time series data. Summary data across entries does not really have a place in bark right now. For example: How should neurons with the same identity be represented across entries? One solution would be to add a more columns to the spikes dataset, though this could quickly grow to impractical dimensions. Another option would be allow root-level datasets that are not timeserires and do not have a timebase. Example:


Neuron | path | name | channel | count | quality | % isi <1ms | p val
----------|--------|--------|------------|--------|---------|--------------|--------
0 | session1/hvc_spikes.csv | 1 | 2 | 1923 | good | .5 | .001
0 | session2/hvc_spikes.csv | 0 | 2 | 4323 | good | 2 | .03
1 | session1/hvc_spikes.csv | 1 | 2 | 542   | mua  | 8 | .6

or for behavior (building a markov model of syllable transistions)

syllable| next | path | count 
----------|-------------|-------|-------------
i | i |  session1/mic_labels.csv | 399
i | a | session1/mic_labels.csv | 132

So instead of having this data in a DB view, we could allow root level csvs *without* metadata. They would not be loaded as Bark Data objects, just pandas Dataframes.

Related idea:

Search for and load a top level notes(.txt | .md | .org) file as text. That's pretty much the main reason to have a root meta.yaml and a plain text file would be more natural. What one would do with the notes string is another question... maybe load it into a database in the future 😜 .

**Comment by kylerbrown** [comment]
@gfetterman I updated the spec, let me know what you think. I tried to add simple relations without much extra. Datasets can be grouped and identified across entries by filename. And I added a bit about top level CSVs.

I think this gives us everything we would need to build relational objects if we wanted them, without burdening Bark with complexities, including NEO-ish objects.

**Comment by gfetterman** [comment]
I agree that there's no currently no place within Bark for storing the results of analysis (which is, ultimately, what you're describing, right? You have to run some analysis on the data to pull out how many "a" syllables were sung, or how many good units an electrode has on day X). Making a place for that is a good idea.

I like the simplicity of your amendments: the source/group parallel structure feels natural, and the explicit-but-not-required paths in root-level CSVs allows flexible linking.

**Comment by kylerbrown** [comment]
Used `dataset` to make an extremely lightweight database implementation. No relations, but included enough information to join `root`s to `entry`s, `entry`s to `datasets`, `column`s to `dataset`s.

Next question is documenting a metadata best practices and conventions for field names.
