### ISSUE TITLE
Use an ISO 8601 timestamp string

### ISSUE THREAD

**Issue by kylerbrown** [kylerbrown/bark#22]
Given the readability of the meta.yaml, why not make the timestamp readable?

old timestamp:
```yaml
timestamp:
    - 1463414451
    - 100000
```
proposed timestamp:
```yaml
timestamp: 2016-05-16T16:00:51.100000+00:00
```

**Comment by gfetterman** [comment]
Simpler, human-readable, not tied to the epoch. I like it.

My only concern: DST. The spec should either require a certain treatment, or explicitly say that no guarantee is made about DST awareness.

**Comment by kylerbrown** [comment]
Good point. The UTC offset should make the timestamp DST aware.

For UTC offset unaware timestamps ("naive" old style) I'll assume timezone is current local time.

New timestamp format:
```yaml
timestamp: 2017-02-27T11:03:21.095541-06:00
```

Alternately, we could stick with naive timestamps, but there would be some ambiguity such as the first hour of DST.

Using the [arrow](https://arrow.readthedocs.io/en/latest/) library to form and parse datetime strings. Not thrilled about this, but it's simpler than using the standard lib.

**Comment by kylerbrown** [comment]
OK, I'm making time parsing function also request a timezone string, people should know which timezone the data were collected in. Defaults to `America/Chicago`.
