### ISSUE TITLE
units of 's' vs 'samples': asymmetrical, confusing, a problem in the future

### ISSUE THREAD

**Issue by gfetterman** [kylerbrown/bark#3]
Having the two common units of time be 's' and 'samples' reveals three problems:
1. Aesthetically displeasing: it's asymmetrical.
2. Obtuse: it can be easy to get wrong, even for the savvy (see [this simple error in bark.py](https://github.com/gfetterman/bark/blob/fd8c7b07e7318f1f827ac007ed5b342e57db125b/bark/bark.py#L177)).
3. Divinatory: it requires us to have perfect future knowledge of units used in the wild. For example, imagine the collision involving a time series of conductances, measured in Siemens (when cast to lowercase). Other collisions are possible when using unit abbreviations.

I propose a standard format for 'units' metadata:

* Fully written out - i.e., "seconds", rather than "s" 
* All lowercase (as previously discussed offline)

This may inspire further metadata, such as "abbreviated unit" or the like, but it addresses the three problems above.

The only concern, as far as I can see, is the problem of interacting with existing data already using the 's' convention for 'seconds'.  A little clean-up code in `bark:read_meta` will paper over this problem, and progressively solve it.

**Comment by kylerbrown** [comment]
This is an interesting idea. Thanks for voicing your opinion.

My thoughts on your three concerns:
1. aesthetics are important, and I agree that this isn't very elegant. 
2. Yes, good catch. And it is indicative of a confusing design choice. 
3. The conversion to lowercase breaks the SI standard, and therefore we shouldn't do that. If we don't do lowercase conversion I think the system is robust.

Here are my concerns:
* Your proposal breaks from the ARF standard. This is my main concern. Let's try to avoid breaking the 1-1 mapping from bark to ARF unless absolutely necessary. Eventually, we may have a single bark/ARF library. Keeping the required attribute values the same across the two standards will make the code clearer.
* The issue with `s` and `samples` is really `samples`, which has no SI abbreviation
* The SI abbreviations are very broadly accepted. Bark is about bringing common standards together to make our work easier. I think SI abbreviations fit that philosophy well. (meters or metres? siemens or mhos? amperes or amps?)

I think you are underestimating the required work-load for this change. Any program that works with event data will need to be modified. Any future programmers will need to know this important nuance between bark and ARF.

Taken together, I feel SI abbreviations are the simplest (in terms of additional labor and design, Arf compatibility) and clearest (zero ambiguity, well documented external standard).
 
Counter proposal: We do a better job of documenting the SI unit convention and carefully explaining the `samples` exception. We also forgive the use of `seconds` in reading event data, but convert it to `s` in the read function, which would propagate to any new datasets.

**Comment by gfetterman** [comment]
Agree on all points.

**Comment by kylerbrown** [comment]
I'm going to reopen this issue so we can draft some better documentation.
