### ISSUE TITLE
estimated physical locations of spike-sorted clusters

### ISSUE THREAD

**Issue by gfetterman** [kylerbrown/bark#43]
We've talked about including the estimated location of a given spike-sorted cluster in the event dataset output by `bark-convert-spyking`. But this information is properly separated into two parts:

1. the physical location of each given channel in a sampled dataset, and
2. which channel is the best candidate for being the "center" of the set of channels the cluster appears on.

With this in mind, I think the following makes the most sense:

+ include in the (`meta` file for the) `bark-convert-spyking` output event dataset the _channel_ number that is the likeliest "center" of the cluster/template.
+ include in the per-channel metadata for the sampled dataset (i.e., the one that was spike-sorted) the physical _location_ of that channel.

Thus, getting the physical coordinates of a cluster is a matter of consulting the metadata for the channel indicated in the metadata for the cluster event dataset.

What do you think?

**Comment by gfetterman** [comment]
(So two pieces of code would be needed:

+ `bark-convert-spyking` would include the `center_channel` attribute for each cluster/template
+ a new program, that may or may not belong in Bark, something like `add-channel-coordinates`, would add the locations (calculated from an input `.prb` file or equivalent) to the metadata for the sampled dataset containing the channels. In a workflow, this step would occur after extraction from the `.rhd` files.)

**Comment by kylerbrown** [comment]
I think this is a great idea. My only concern is the amount of effort involved. If it's easy, absolutely. Otherwise we can share functions for accessing SC data from it's original format nested within an entry.

**Comment by gfetterman** [comment]
The modification to `bark-convert-spyking` is already done.

As for the other thing, `add-channel-coordinates`, I've already automated `.prb` file generation. It shouldn't be too much work to adapt that code for this purpose.
