### ISSUE TITLE
Small simplifications to bark.py

### ISSUE THREAD

**Issue by gfetterman** [kylerbrown/bark#5]
Following up on our offline conversation about tightening up bark.py, the following jump out at me:
1. Root creation function calls: [`Root.read`](https://github.com/gfetterman/bark/blob/d7be08e02c78139a8bcfb1fcb1f3ccaff250ebfa/bark/bark.py#L97) and [`read_root`](https://github.com/gfetterman/bark/blob/d7be08e02c78139a8bcfb1fcb1f3ccaff250ebfa/bark/bark.py#L294) do the same thing, line-for-line. **Proposal**: keep `Root.read` as-is and change `read_root` into a call to `Root.read`. As a consequence, also change the invocation of `read_root` at the end of [`create_root`](https://github.com/gfetterman/bark/blob/d7be08e02c78139a8bcfb1fcb1f3ccaff250ebfa/bark/bark.py#L282) to an invocation of `Read.root`.
2. Given that UUIDs are now stored as strings in the `attrs` dictionaries, [`get_uuid`](https://github.com/gfetterman/bark/blob/d7be08e02c78139a8bcfb1fcb1f3ccaff250ebfa/bark/bark.py#L407) seems like an unnecessary holdover from ARF. **Proposal**: delete it.
3. The combination of [`timestamp_to_datetime`](https://github.com/gfetterman/bark/blob/d7be08e02c78139a8bcfb1fcb1f3ccaff250ebfa/bark/bark.py#L386) and appropriate calls to methods of `datetime` objects fully subsumes the functionality of both [`timestamp_to_float`](https://github.com/gfetterman/bark/blob/d7be08e02c78139a8bcfb1fcb1f3ccaff250ebfa/bark/bark.py#L392) and [`parse_timestamp_string`](https://github.com/gfetterman/bark/blob/d7be08e02c78139a8bcfb1fcb1f3ccaff250ebfa/bark/bark.py#L397). **Proposal**: delete both of the latter functions and let users decide what to do with `datetime` objects in their own code. **Weaker alternative**: keep them, but refactor them into wrappers around `timestamp_to_datetime`.
4. Users are explicitly warned not to use [`load_dat`](https://github.com/gfetterman/bark/blob/d7be08e02c78139a8bcfb1fcb1f3ccaff250ebfa/bark/bark.py#L194) at all. **Proposal**: delete it.

**Comment by kylerbrown** [comment]
1. Sounds great
2. Delete
3. No. A function called timestamp_to_datetime cannot turn something that isn't a timestamp into something that isn't a datetime. I don't think these functions should be combined. I use parse_timestamp_string in any cli tool the writes entries, it's pretty useful as is. The other two are arf API I believe, and are also frequently used. Maybe the two converters to datetime could be combined. But the cost is fixing a bunch of external code. If you like, put the string logic in timestamp_to_datetime, but keep the parse_timestamp_string API maybe with a depreciation warning. Add tests for the barkutils to make extra sure they don't break.
4. Delete

**Comment by gfetterman** [comment]
Re point 3, if external code already relies on those functions, it is probably simpler then to just leave them as-is.
I'll do points 1, 2, and 4.

**Comment by kylerbrown** [comment]
thanks Graham!
