### ISSUE TITLE
give a helpful error on orphan .metas

### ISSUE THREAD

**Issue by kylerbrown** [kylerbrown/bark#9]
If an entry has X.meta but not X, give a useful error.

**Comment by gfetterman** [comment]
I haven't come across this problem yet (just haven't been using it long enough).
Should it be a "useful-error-leading-to-freakout-and-die" or "useful-warning-then-skip" kind of situation?

**Comment by kylerbrown** [comment]
@gfetterman I'm going with freakout and die for now.
